// This code conforms with the UFC specification version 2018.1.0
// and was automatically generated by FFC version 2019.1.0.post0.
//
// This code was generated with the following parameters:
//

//  add_tabulate_tensor_timing:     False
//  convert_exceptions_to_warnings: False
//  cpp_optimize:                   True
//  cpp_optimize_flags:             '-O2'
//  epsilon:                        1e-14
//  error_control:                  False
//  external_include_dirs:          ['/usr/local/include', '/usr/local/slepc-32/includ
//                                  e', '/usr/local/petsc-32/include', '/usr/include/m
//                                  pich', '/usr/include/hdf5/mpich', '/usr/include/ei
//                                  gen3', '/usr/local/lib/python3.6/dist-packages/ffc
//                                  /backends/ufc']
//  external_includes:              ''
//  external_libraries:             ''
//  external_library_dirs:          ''
//  form_postfix:                   False
//  format:                         'ufc'
//  generate_dummy_tabulate_tensor: False
//  max_signature_length:           0
//  no-evaluate_basis_derivatives:  True
//  optimize:                       True
//  precision:                      None
//  quadrature_degree:              None
//  quadrature_rule:                None
//  representation:                 'auto'
//  split:                          False

#include "ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f.h"

// Based on https://gcc.gnu.org/wiki/Visibility
#if defined _WIN32 || defined __CYGWIN__
    #ifdef __GNUC__
        #define DLL_EXPORT __attribute__ ((dllexport))
    #else
        #define DLL_EXPORT __declspec(dllexport)
    #endif
#else
    #define DLL_EXPORT __attribute__ ((visibility ("default")))
#endif

ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_cell_integral_main_otherwise::ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_cell_integral_main_otherwise() : ufc::cell_integral()
{

}

ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_cell_integral_main_otherwise::~ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_cell_integral_main_otherwise()
{

}

const std::vector<bool> & ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_cell_integral_main_otherwise::enabled_coefficients() const
{
static const std::vector<bool> enabled({true, true});
return enabled;
}

void ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_cell_integral_main_otherwise::tabulate_tensor(double * A,
                                    const double * const * w,
                                    const double * coordinate_dofs,
                                    int cell_orientation) const
{
    // This function was generated using 'uflacs' representation
    // with the following integrals metadata:
    // 
    // num_cells:         None
    // optimize:          True
    // precision:         16
    // quadrature_degree: 0
    // quadrature_rule:   'default'
    // representation:    'uflacs'
    // 
    // and the following integral 0 metadata:
    // 
    // estimated_polynomial_degree: 0
    // optimize:                    True
    // precision:                   16
    // quadrature_degree:           0
    // quadrature_rule:             'default'
    // representation:              'uflacs'
    // Quadrature rules
    alignas(32) static const double weights1[1] = { 0.5 };
    // Precomputed values of basis functions and precomputations
    // FE* dimensions: [entities][points][dofs]
    // PI* dimensions: [entities][dofs][dofs] or [entities][dofs]
    // PM* dimensions: [entities][dofs][dofs]
    alignas(32) static const double FE19_C0_D01_Q1[1][1][2] = { { { -1.0, 1.0 } } };
    // Unstructured piecewise computations
    const double w0_d1_c0 = w[0][0] * FE19_C0_D01_Q1[0][0][0] + w[0][2] * FE19_C0_D01_Q1[0][0][1];
    const double J_c0 = coordinate_dofs[0] * FE19_C0_D01_Q1[0][0][0] + coordinate_dofs[2] * FE19_C0_D01_Q1[0][0][1];
    const double J_c3 = coordinate_dofs[1] * FE19_C0_D01_Q1[0][0][0] + coordinate_dofs[5] * FE19_C0_D01_Q1[0][0][1];
    const double J_c1 = coordinate_dofs[0] * FE19_C0_D01_Q1[0][0][0] + coordinate_dofs[4] * FE19_C0_D01_Q1[0][0][1];
    const double J_c2 = coordinate_dofs[1] * FE19_C0_D01_Q1[0][0][0] + coordinate_dofs[3] * FE19_C0_D01_Q1[0][0][1];
    double w0_d0_c0 = 0.0;
    for (int ic = 0; ic < 2; ++ic)
        w0_d0_c0 += w[0][ic] * FE19_C0_D01_Q1[0][0][ic];
    const double w1_d1_c0 = w[1][0] * FE19_C0_D01_Q1[0][0][0] + w[1][2] * FE19_C0_D01_Q1[0][0][1];
    const double J_c0 = coordinate_dofs[0] * FE19_C0_D01_Q1[0][0][0] + coordinate_dofs[2] * FE19_C0_D01_Q1[0][0][1];
    const double J_c3 = coordinate_dofs[1] * FE19_C0_D01_Q1[0][0][0] + coordinate_dofs[5] * FE19_C0_D01_Q1[0][0][1];
    const double J_c1 = coordinate_dofs[0] * FE19_C0_D01_Q1[0][0][0] + coordinate_dofs[4] * FE19_C0_D01_Q1[0][0][1];
    const double J_c2 = coordinate_dofs[1] * FE19_C0_D01_Q1[0][0][0] + coordinate_dofs[3] * FE19_C0_D01_Q1[0][0][1];
    double w1_d0_c0 = 0.0;
    for (int ic = 0; ic < 2; ++ic)
        w1_d0_c0 += w[1][ic] * FE19_C0_D01_Q1[0][0][ic];
    const double w0_d1_c1 = w[0][3] * FE19_C0_D01_Q1[0][0][0] + w[0][5] * FE19_C0_D01_Q1[0][0][1];
    double w0_d0_c1 = 0.0;
    for (int ic = 0; ic < 2; ++ic)
        w0_d0_c1 += w[0][ic + 3] * FE19_C0_D01_Q1[0][0][ic];
    const double w1_d1_c1 = w[1][3] * FE19_C0_D01_Q1[0][0][0] + w[1][5] * FE19_C0_D01_Q1[0][0][1];
    double w1_d0_c1 = 0.0;
    for (int ic = 0; ic < 2; ++ic)
        w1_d0_c1 += w[1][ic + 3] * FE19_C0_D01_Q1[0][0][ic];
    const double J_c0 = coordinate_dofs[0] * FE19_C0_D01_Q1[0][0][0] + coordinate_dofs[2] * FE19_C0_D01_Q1[0][0][1];
    const double J_c3 = coordinate_dofs[1] * FE19_C0_D01_Q1[0][0][0] + coordinate_dofs[5] * FE19_C0_D01_Q1[0][0][1];
    const double J_c1 = coordinate_dofs[0] * FE19_C0_D01_Q1[0][0][0] + coordinate_dofs[4] * FE19_C0_D01_Q1[0][0][1];
    const double J_c2 = coordinate_dofs[1] * FE19_C0_D01_Q1[0][0][0] + coordinate_dofs[3] * FE19_C0_D01_Q1[0][0][1];
    alignas(32) double sp[54];
    sp[0] = J_c0 * J_c3;
    sp[1] = J_c1 * J_c2;
    sp[2] = sp[0] + -1 * sp[1];
    sp[3] = J_c0 / sp[2];
    sp[4] = w0_d1_c0 * sp[3];
    sp[5] = -1 * J_c1 / sp[2];
    sp[6] = w0_d0_c0 * sp[5];
    sp[7] = sp[4] + sp[6];
    sp[8] = J_c0 * J_c3;
    sp[9] = J_c1 * J_c2;
    sp[10] = sp[8] + -1 * sp[9];
    sp[11] = J_c0 / sp[10];
    sp[12] = w1_d1_c0 * sp[11];
    sp[13] = -1 * J_c1 / sp[10];
    sp[14] = w1_d0_c0 * sp[13];
    sp[15] = sp[12] + sp[14];
    sp[16] = sp[7] + -1 * sp[15];
    sp[17] = sp[16] * sp[16];
    sp[18] = w0_d1_c1 * sp[3];
    sp[19] = w0_d0_c1 * sp[5];
    sp[20] = sp[18] + sp[19];
    sp[21] = w1_d1_c1 * sp[11];
    sp[22] = w1_d0_c1 * sp[13];
    sp[23] = sp[21] + sp[22];
    sp[24] = sp[20] + -1 * sp[23];
    sp[25] = sp[24] * sp[24];
    sp[26] = sp[17] + sp[25];
    sp[27] = J_c3 / sp[2];
    sp[28] = w0_d0_c0 * sp[27];
    sp[29] = -1 * J_c2 / sp[2];
    sp[30] = w0_d1_c0 * sp[29];
    sp[31] = sp[28] + sp[30];
    sp[32] = J_c3 / sp[10];
    sp[33] = w1_d0_c0 * sp[32];
    sp[34] = -1 * J_c2 / sp[10];
    sp[35] = w1_d1_c0 * sp[34];
    sp[36] = sp[33] + sp[35];
    sp[37] = sp[31] + -1 * sp[36];
    sp[38] = sp[37] * sp[37];
    sp[39] = w0_d0_c1 * sp[27];
    sp[40] = w0_d1_c1 * sp[29];
    sp[41] = sp[39] + sp[40];
    sp[42] = w1_d0_c1 * sp[32];
    sp[43] = w1_d1_c1 * sp[34];
    sp[44] = sp[42] + sp[43];
    sp[45] = sp[41] + -1 * sp[44];
    sp[46] = sp[45] * sp[45];
    sp[47] = sp[38] + sp[46];
    sp[48] = sp[26] + sp[47];
    sp[49] = J_c0 * J_c3;
    sp[50] = J_c1 * J_c2;
    sp[51] = sp[49] + -1 * sp[50];
    sp[52] = std::abs(sp[51]);
    sp[53] = sp[48] * sp[52];
    alignas(32) double BF0 = {};
    // Only 1 quadrature point, no loop
    {
        const double fw0 = sp[53] * weights1[0];
        BF0 += fw0;
    }
    A[0] = 0.0;
    A[0] += BF0;
}

extern "C" DLL_EXPORT ufc::cell_integral * create_ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_cell_integral_main_otherwise()
{
  return new ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_cell_integral_main_otherwise();
}


ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main() : ufc::form()
{
    // Do nothing
}

ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::~ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main()
{
    // Do nothing
}

const char * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::signature() const
{
    return "3ce54aac751d92eab58366b8f60efdd55bd0874ceeb04977777b8eca62b3df5a590e42639135fa977a6e3652f9436783254288893c4fcf0bb4ed9b246039e4b1";
}

std::size_t ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::rank() const
{
    return 0;
}

std::size_t ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::num_coefficients() const
{
    return 2;
}

std::size_t ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::original_coefficient_position(std::size_t i) const
{
    if (i >= 2)
    {
        throw std::runtime_error("Invalid original coefficient index.");
    }
    static const std::vector<std::size_t> position = {0, 1};
    return position[i];
}

ufc::finite_element * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_coordinate_finite_element() const
{
    return create_ffc_element_a1497b82f3e381cb68258a25a6e30cf065c7f97a_finite_element_main();
}

ufc::dofmap * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_coordinate_dofmap() const
{
    return create_ffc_element_a1497b82f3e381cb68258a25a6e30cf065c7f97a_dofmap_main();
}

ufc::coordinate_mapping * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_coordinate_mapping() const
{
    return create_ffc_coordinate_mapping_5bb505d481809b53dc9c61e7300a2a039ee88f61_coordinate_mapping_main();
}

ufc::finite_element * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_finite_element(std::size_t i) const
{
    switch (i)
    {
    case 0:
        return create_ffc_element_a1497b82f3e381cb68258a25a6e30cf065c7f97a_finite_element_main();
    case 1:
        return create_ffc_element_a1497b82f3e381cb68258a25a6e30cf065c7f97a_finite_element_main();
    default:
        return nullptr;
    }
}

ufc::dofmap * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_dofmap(std::size_t i) const
{
    switch (i)
    {
    case 0:
        return create_ffc_element_a1497b82f3e381cb68258a25a6e30cf065c7f97a_dofmap_main();
    case 1:
        return create_ffc_element_a1497b82f3e381cb68258a25a6e30cf065c7f97a_dofmap_main();
    default:
        return nullptr;
    }
}

std::size_t ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::max_cell_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::max_exterior_facet_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::max_interior_facet_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::max_vertex_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::max_custom_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::max_cutcell_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::max_interface_subdomain_id() const
{
    return 0;
}

std::size_t ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::max_overlap_subdomain_id() const
{
    return 0;
}

bool ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::has_cell_integrals() const
{
    return true;
}

bool ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::has_exterior_facet_integrals() const
{
    return false;
}

bool ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::has_interior_facet_integrals() const
{
    return false;
}

bool ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::has_vertex_integrals() const
{
    return false;
}

bool ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::has_custom_integrals() const
{
    return false;
}

bool ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::has_cutcell_integrals() const
{
    return false;
}

bool ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::has_interface_integrals() const
{
    return false;
}

bool ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::has_overlap_integrals() const
{
    return false;
}

ufc::cell_integral * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_cell_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::exterior_facet_integral * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_exterior_facet_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::interior_facet_integral * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_interior_facet_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::vertex_integral * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_vertex_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::custom_integral * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_custom_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::cutcell_integral * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_cutcell_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::interface_integral * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_interface_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::overlap_integral * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_overlap_integral(std::size_t subdomain_id) const
{
    return nullptr;
}

ufc::cell_integral * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_default_cell_integral() const
{
    return create_ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_cell_integral_main_otherwise();
}

ufc::exterior_facet_integral * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_default_exterior_facet_integral() const
{
    return nullptr;
}

ufc::interior_facet_integral * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_default_interior_facet_integral() const
{
    return nullptr;
}

ufc::vertex_integral * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_default_vertex_integral() const
{
    return nullptr;
}

ufc::custom_integral * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_default_custom_integral() const
{
    return nullptr;
}

ufc::cutcell_integral * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_default_cutcell_integral() const
{
    return nullptr;
}

ufc::interface_integral * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_default_interface_integral() const
{
    return nullptr;
}

ufc::overlap_integral * ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main::create_default_overlap_integral() const
{
    return nullptr;
}

extern "C" DLL_EXPORT ufc::form * create_ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main()
{
  return new ffc_form_9ab703d1dea7ed31f709d3f25985713c2419ab6f_form_main();
}

